### ISSUE TITLE
TaskRunner tracking bug

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5512]
This issue is intended to help me organize what’s done and needs doing for TaskRunner.

 * [x] [API](https://github.com/square/okhttp/pull/5461)
 * [x] [Initial implementation](https://github.com/square/okhttp/pull/5485)
 * [x] [ConnectionPool](https://github.com/square/okhttp/pull/5494)
 * [x] [DiskLruCache](https://github.com/square/okhttp/pull/5496)
 * [x] [HTTP/2 writer and push](https://github.com/square/okhttp/pull/5502)
 * [x] [WebSockets](https://github.com/square/okhttp/pull/5510)
 * [x] MockWebServer
 * [x] HTTP/2 listeners
 * [x] Daemon threads
 * [x] Fewer context switches ([details](https://github.com/square/okhttp/pull/5510#discussion_r329355091))
 * [x] Consistent queue and task names
 * [x] Strict mode and/or other diagnostics for stuck queues ([details](https://github.com/square/okhttp/pull/5496))
 * [x] Tools for understanding real-world use ([details](https://github.com/square/okhttp/pull/5532#issuecomment-538617152))
 * [x] Re-evaluate how tryCancel() opt-in vs. opt-out
 * [x] [Better task names](https://github.com/square/okhttp/pull/5535)

See also
 * [Simplify test code](https://github.com/square/okhttp/pull/5507)
 * [Detect HTTP/2 liveness](https://github.com/square/okhttp/issues/3146)

**Comment by swankjesse** [comment]
To improve visibility I think I'll borrow from what we do for HTTP/2 frames: use logger.fine() to print events and metrics. If you know it exists you can turn it on, but no public API.

**Comment by swankjesse** [comment]
I wanna build debug logging for tasks. Here’s a sketch of a sample log:

```
Q1 ▌ scheduled after 100 ms: OkHttp example.com ping
Q1 ▌▌ scheduled after 200 ms: OkHttp example.com[3] writeSynReset
Q1 ▌▌ starting: OkHttp example.com ping
Q1 ▌▌ executed in 130 ms (next after 100 ms): OkHttp example.com ping
Q1 ▌▌ starting (31 ms late): OkHttp example.com[3] writeSynReset
Q1 ▌▌ executed in 2 ms: OkHttp example.com[3] writeSynReset
Q2 ▌ posted: OkHttp ConnectionPool
```

Notes:

 * Q1, Q2 etc. is queue name. This is a process-wide ID.
 * ▌▌ is queue size in tasks. This includes task being just-added or just-completed.
 * _scheduled_ for delayed tasks, _posted_ for immediate tasks.
 * units are ms, µs, or s. No nanos in logs; just truncate to 0 µs.
 * "starting" includes start delay like _(31 ms late)_ if task start is more than 10 ms later than scheduled. This will be due to busy CPU or a preceding task going overtime.
 * need to measure execution time!

These logs will be off by default. Enable `FINE` logging on `TaskRunner` to get logs.

**Comment by Egorand** [comment]
A couple thoughts:
- Probably worth keeping logs indented to the same level after the queue size, otherwise it feels like the logs with the same indentation are grouped, while they're not. Perhaps having a uniform indentation that grows if the queue gets bigger could work?

```
Q1 ▌     scheduled after 100 ms: OkHttp example.com ping
Q1 ▌▌    scheduled after 200 ms: OkHttp example.com[3] writeSynReset
Q1 ▌▌▌   starting: OkHttp example.com ping
Q1 ▌▌▌▌  executed in 130 ms (next after 100 ms): OkHttp example.com ping
Q1 ▌▌    starting (31 ms late): OkHttp example.com[3] writeSynReset
Q1 ▌▌▌▌▌ executed in 2 ms: OkHttp example.com[3] writeSynReset
Q2 ▌▌▌▌▌▌▌▌▌▌ posted: OkHttp ConnectionPool
Q2 ▌▌▌▌▌▌▌    posted: OkHttp ConnectionPool
Q2 ▌▌▌▌▌▌▌▌▌  posted: OkHttp ConnectionPool
Q2 ▌     posted: OkHttp ConnectionPool
```
- How about printing **scheduled**, **starting**, **executed** and **posted** in bold?

**Comment by yschimke** [comment]
@swankjesse Nice work on this, impressive to see the progression!

**Comment by swankjesse** [comment]
I think I'm ready to call this complete. Anything else you wanna see for observability or troubleshooting?

**Comment by yschimke** [comment]
@swankjesse let's follow up with that based on working through flaky CI tests.  That's my main goal - can we use our own tools to after the fact debug

**Comment by swankjesse** [comment]
No further action for this issue. Will work through flaky tests!
